version: '3.8'

services:
  web:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    networks:
      custom_network:
        ipv4_address: ${CONTAINER_IP}
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost # Example environment variable for Vite
    restart: always

networks:
  custom_network:
    external:
      name: my_net
